---
kind: pipeline
type: kubernetes
name: callisto-ui

platform:
  os: linux
  arch: amd64

steps:
  - name: code analysis
    image: sonarsource/sonar-scanner-cli
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=$${DRONE_REPO} -Dsonar.organization=ukhomeoffice -Dsonar.projectName=$${DRONE_REPO} -Dsonar.branch.name=$${DRONE_BRANCH} -Dsonar.sources=./src -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info    

  - name: install dependencies
    image: &node_image # the version we're targeting for productio
      node:16.15.0
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm install

  - name: lint project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run lint
      - npx stylelint "**/*.scss"
    depends_on:
      - install dependencies

  - name: test project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run test
    depends_on:
      - install dependencies

  - name: build project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      VITE_KC_URL:
        from_secret: kc_url_dev
      VITE_KC_REALM:
        from_secret: kc_realm_dev
      VITE_KC_CLIENTID:
        from_secret: kc_clientid_dev
      VITE_TIMECARD_API_URL: "https://timecard.dev.callisto.homeoffice.gov.uk/"
      VITE_ACCRUALS_API_URL: "https://accruals.dev.callisto.homeoffice.gov.uk/"                        
    commands:
      - npm run build
    depends_on:
      - install dependencies

  - name: upload to S3
    image: plugins/s3
    settings:
      bucket: ho-callisto-dev
      region: eu-west-2
      access_key:
        from_secret: s3_aws_access_key_id
      secret_key:
        from_secret: s3_aws_secret_access_key
      source: dist/**/*
      strip_prefix: dist/
      target: dev/main
    when:
      event: push
      branch:
        - main
    depends_on:
      - build project

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - callisto-ui

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
