---
kind: pipeline
type: kubernetes
name: callisto-ui

platform:
  os: linux
  arch: amd64

steps:
  - name: install dependencies
    image: &node_image # The version we're targeting for production
      node:16.15.0
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm install

  - name: lint project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run lint
      - npx stylelint "**/*.scss"
    depends_on:
      - install dependencies

  - name: test project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run test
    depends_on:
      - install dependencies

  - name: build project
    image: *node_image
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm run build
    depends_on:
      - install dependencies

---
kind: pipeline
type: kubernetes
name: deploy

trigger:
  status:
    - success

depends_on:
  - callisto-ui

steps:
  # - name: deploy
  #   pull: if-not-exists
  #   image: quay.io/ukhomeofficedigital/kd:v1.18.0
  #   commands:
  #     - bin/deploy.sh
  #   environment:
  #     IMAGE_URL: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/<repo>
  #     # KUBE_TOKEN_ACP_NOTPROD:
  #     #   from_secret: kube_token_acp_notprod
  #   when:
  #     event:
  #       - promote

  - name: lint_helm_chart
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    environment:
      VALUES_FILE: helm/values.yaml
    commands:
      - helm lint --strict -f $${VALUES_FILE} helm
    when:
      # branch:
      # - main
      # - feature/*
      event:
        - push

  - name: deploy_to_dev_helm
    image: quay.io/ukhomeofficedigital/helm:v3.5.4
    environment:
      RELEASE_NAME: callisto
      VALUES_FILE: helm/values.yaml
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_CLUSTER_NAME: acp-notprod
      KUBE_NAMESPACE: sas-callisto-dev
      KUBE_TOKEN: test # from_secret: kube_token_acp_notprod
    commands:
      - /setup-kubeconfig.sh
      - helm upgrade --debug -f $${VALUES_FILE} --namespace=$${KUBE_NAMESPACE} $${RELEASE_NAME} helm --set image.tag=$${DRONE_COMMIT_SHA} -i --wait --timeout 10m --history-max 5
    when:
      # branch:
      # - main
      # - feature/*
      event:
        - push
    depends_on:
      - lint_helm_chart

# services:
#   - name: docker
#     image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
#     # environment:
#     #   DOCKER_TLS_CERTDIR: ''

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - callisto-ui
  - deploy

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: callisto-tech-notifications
      username: Drone
      template: |
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
