---
kind: pipeline
type: kubernetes
name: callisto-ui

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: quay.io/ukhomeofficedigital/node-artifactory:14
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm config ls -l
      - npm install || cat /home/node/.npm/_logs/*
      - npm run lint
      - npm run test
      - npm run build
