---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: quay.io/ukhomeofficedigital/node-artifactory:14
    environment:
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
    commands:
      - npm install
      - npm run lint
      - npx stylelint "**/*.scss"
      - npm run test
      - npm run build

---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure
  event:
    - push

depends_on:
  - build

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: callisto-tech-notifications
      username: Drone
      template: >
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}

        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{ build.message }}
        Repo: {{ repo.name }}

        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>

        Author: {{ build.author }}
