version: '3.3'

services:
  web:
    image: nginx:1.19.2-alpine
    ports:
      - 9090
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - callisto

networks:
  callisto:
    name: callisto-localdev_callisto
    driver: bridge
    external: true
