# It allows to develop the code while running app as Docker container without the need to restart it.
version: '3.3'

services:
  web:
    image: node:17-alpine
    ports:
      - '50001:9090'
    volumes:
      - .:/app
      - './node_modules_linux:/app/node_modules'
    networks:
      - callisto
    entrypoint: 'npm run localdev'
    working_dir: /app

networks:
  callisto:
    name: callisto-localdev_callisto
    driver: bridge
    external: true
