apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: callisto-web
  # labels:
  #   # @Note: this label tells the cluster issuer to use the DNS01 Route53 solver instead of the default HTTP01 solver
  #   cert-manager.io/solver: route53
spec: 
  secretName: callisto-web-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: web.dev.callisto.homeoffice.gov.uk
  dnsNames: 
    - web.dev.callisto.homeoffice.gov.uk
    - {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-web.dev.callisto.homeoffice.gov.uk
  # acme:
  #   config:
  #     - http01: 
  #       ingressClass: nginx
  #     domains: 
  #       - web.dev.callisto.homeoffice.gov.uk
  ipAddresses:
    - 127.0.0.1

