apiVersion: v1
kind: ConfigMap
metadata:
  name: default-conf
data:
  default.conf.template: | 
{{ .Files.Get "config/default.conf.template" | indent 4 }}
  nginx.conf: | 
{{ .Files.Get "config/nginx.conf" | indent 4 }}