---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: induction
          image: quay.io/ukhomeofficedigital/hocs-test-viewer
          imagePullPolicy: IfNotPresent
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sas-callisto-test-results
                  key: access_key_id
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sas-callisto-test-results
                  key: secret_access_key
            - name: DASHBOARD_BUCKET
              valueFrom:
                secretKeyRef:
                  name: sas-callisto-test-results
                  key: name
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
