---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: callisto
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callisto
      service: callisto
  template:
    metadata:
      labels:
        name: callisto
        service: callisto
    spec:
      containers:
        - name: nginx
          image: {{.Values.image.repo}}{{.Values.image.name}}:{{.Values.image.version}}
          imagePullPolicy: IfNotPresent
           securityContext:
              runAsNonRoot: true
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
          - name: MYSUPERSECRET
            valueFrom:
              secretKeyRef:
                name: callisto-secret
                key: mysupersecret
