---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: callisto
  labels:
    app: callisto
    cert-manager.io/solver: route53
  annotations:
    # ingress.kubernetes.io/ssl-passthrough: 'true' # instructs the controller to send TLS connections directly to the backend instead of letting NGINX decrypt the communication
    cert-manager.io/enabled: 'true'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    # cert-manager.io/cluster-issuer: 'letsencrypt-staging'
    kubernetes.io/ingress.class: 'nginx-external' # needs changing to internal
    kubernetes.io/backend-protocol: 'HTTPS'
    # kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/server-snippet: |
      location /test_sk2022 {
        return 200 "<html><head></head><body>Success</body></html>";
      }
spec:
  tls:
    - hosts:
        - {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-web.dev.callisto.homeoffice.gov.uk 
        - web.dev.callisto.homeoffice.gov.uk
      secretName: callisto-web-tls
  rules:
    - host: {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-web.dev.callisto.homeoffice.gov.uk 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-callisto-web
                port:
                  number: 3000
    - host: web.dev.callisto.homeoffice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: callisto-web
                port:
                  number: 3000
