---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    cert-manager.io/solver: route53
  annotations:
    cert-manager.io/enabled: 'true'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    kubernetes.io/ingress.class: 'nginx-internal'
    ingress.kubernetes.io/backend-protocol: 'HTTPS'
    ingress.kubernetes.io/configuration-snippet: |-
      return 200 ""<html><head></head><body>Success</body></html>"
spec:
  # tls:
  #   - hosts:
  #       - {{ .Values.global.ingress.host }}
      # secretName: {{ .Chart.Name }}-ingress # the name of the kubernetes secret in your namespace with tls.crt and tls.key
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
