---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  # labels:
  #   cert-manager.io/solver: route53
  annotations:
    kubernetes.io/ingress.class: 'nginx-internal'
    # cert-manager.io/enabled: 'true'
    # ingress.kubernetes.io/force-ssl-redirect: 'true'
    # ingress.kubernetes.io/backend-protocol: 'HTTPS'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    ingress.kubernetes.io/configuration-snippet: |
      location ~* "^/" {
        return 200 "<html><head></head><body>Success</body></html>";
      }
spec:
  # tls:
  #   - hosts:
  #       - {{ .Values.global.ingress.host }}
      # secretName: {{ .Chart.Name }}-ingress # the name of the kubernetes secret in your namespace with tls.crt and tls.key
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: /test
            pathType: Exact
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
