---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: callisto
  labels:
    app: callisto
    cert-manager.io/solver: route53 # needed if site is internal
  annotations:
    ingress.kubernetes.io/ssl-passthrough: 'true'
    cert-manager.io/enabled: 'true'
    ingress.kubernetes.io/force-ssl-redirect: 'true'
    ingress.kubernetes.io/ssl-redirect: 'true'
    # ingress.kubernetes.io/affinity: cookie
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-staging'
    # ingress.kubernetes.io/session-cookie-name: ingress
    kubernetes.io/ingress.class: 'nginx-external'
    kubernetes.io/backend-protocol: 'HTTPS'
    kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/server-snippet: |
      location /test_sk2022 {
        return 200 "<html><head></head><body>Success</body></html>";
      }
spec:
  tls:
    - hosts:
        - {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-web.dev.callisto.homeoffice.gov.uk 
        - web.dev.callisto.homeoffice.gov.uk
      secretName: callisto-web-tls # the name of the kubernetes secret that cert-manager will manage in your namespace with tls.crt and tls.key
  rules:
    - host: {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-web.dev.callisto.homeoffice.gov.uk 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name | regexFind "([A-Za-z]+-\\d+)" | lower }}-callisto-web
                port:
                  number: 3000
    - host: web.dev.callisto.homeoffice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: callisto-web
                port:
                  number: 3000
