---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Chart.Name }}
#   # labels:
#   #   cert-manager.io/solver: route53
#   annotations:
#     # kubernetes.io/ingress.class: 'nginx-internal'
#     # cert-manager.io/enabled: 'true'
#     # ingress.kubernetes.io/force-ssl-redirect: 'true'
#     # ingress.kubernetes.io/backend-protocol: 'HTTPS'
#     # nginx.ingress.kubernetes.io/configuration-snippet: |
#     #   return 200 "<html><head></head><body>Success</body></html>";
# spec:
#   # ingressClassName: nginx
#   # tls:
#   #   - hosts:
#   #       - {{ .Values.global.ingress.host }}
#       # secretName: {{ .Chart.Name }}-ingress # the name of the kubernetes secret in your namespace with tls.crt and tls.key
#   rules:
#     - host: {{ .Values.global.ingress.host }}
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Values.service.name }}
#                 port:
#                   number: {{ .Values.service.port }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: callisto
  labels:
    app: callisto
  annotations:
    kubernetes.io/ingress.class: 'nginx-external'
    kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/rewrite-target: /$1
    ingress.kubernetes.io/server-snippet: |
      location /test_sk2022 {
        return 200 "<html><head></head><body>Success</body></html>";
      }
spec:
  # ingressClassName: nginx
  rules:
    - host: web.dev.callisto.homeoffice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: callisto-web
                port:
                  number: 3000


# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: {{ .Chart.Name }}
#   annotations:
#     kubernetes.io/ingress.class: 'nginx-internal'
#     # cert-manager.io/enabled: 'true'
#     # ingress.kubernetes.io/force-ssl-redirect: 'true'
#     # ingress.kubernetes.io/backend-protocol: 'HTTPS'
#     ingress.kubernetes.io/configuration-snippet: |
#       return 200 "<html><head></head><body>Success</body></html>";
# spec:
#   # ingressClassName: nginx-internal
#   rules:
#     - host: {{ .Values.global.ingress.host }}
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: {{ .Values.service.name }}
#               servicePort: {{ .Values.service.port }}
#   # tls:
#   #   - hosts:
#   #       - {{ .Values.global.ingress.host }}
#       # secretName: {{ .Chart.Name }}-ingress # the name of the kubernetes secret in your namespace with tls.crt and tls.key
