---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - name: https
      port: {{ .Values.port }}
      protocol: TCP
