# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: callisto
# spec:
#   selector:
#     name: callisto
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 80
#       targetPort: 4000
