name: test

service:
  name: callisto-web
  port: 3000

replicaCount: 1

resources:
  requests:
    memory: '512Mi'
    cpu: '500m'
  limits:
    memory: '1Gi'
    cpu: '1500m'

image:
  repo: quay.io/ukhomeofficedigital/
  name: developer-induction
  version: latest

global:
  ingress:
    host: web.dev.callisto.homeoffice.gov.uk
