name: Docker
on:
  push:
    branches:
      - main
      - '**EAHW-**'
      - '**eahw-**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
      VITE_KC_URL: "https://keycloak.callisto.localhost/auth" 
      VITE_KC_REALM: "callisto" 
      VITE_KC_CLIENTID: "callistoreactclient" 
      VITE_TIMECARD_API_URL: "https://timecard-restapi.callisto.localhost/" 
      VITE_ACCRUALS_API_URL: "https://accruals-restapi.callisto.localhost/"
      QUAY_REGISTRY: quay.io/ukhomeofficedigital
      QUAY_REPO_NAME: callisto-ui
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'
    - run: npm ci
    - run: npm run lint
    - run: npx stylelint "**/*.scss"
    - run: npm run test
    - run: npm run build --if-present

    - name: Get Image Tag
      id: image-tags
      run: |
          if [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "image_tag=latest" >> $GITHUB_ENV
          fi
          if [[ $GITHUB_REF_NAME =~ (eahw-[0-9]*|EAHW-[0-9]*) ]] && TAG=${match/#E/E}${BASH_REMATCH/#E/E}; then
            echo "image_tag=${TAG}" >> $GITHUB_ENV
          fi

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ QUAY_REPO_NAME }}
        tags: ${{ env.image_tag }}
        containerfiles: |
          ./Dockerfile
    
    - name: Push image to Quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.QUAY_REGISTRY}}
        username: ${{ secrets.QUAY_ROBOT_NAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

